AppTuitlon/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from AppTuitlon import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
   
    path('', views.inicio, name="Inicio"),
    path('tuitlear/', views.tuitlear, name="Tuitlear"),
    path('tuitl/list', views.TuitlList.as_view(), name='List'),
    path(r'^(?P<pk>\d+)$', views.TuitlDetalle.as_view(), name='Detail'),
    path(r'^borrar/(?P<pk>\d+)$', views.TuitlDelete.as_view(), name='Delete'),
    path('login', views.login_request, name = 'Login'),
    path('logout', LogoutView.as_view(template_name='AppTuitlon/logout.html'), name='Logout'),
    path('register', views.register, name = 'Registrarse'),
    path("editUser", views.editUser, name='Editar Usuario'),
    path('addImg', views.addImg, name='Subir Avatar'),


]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoTuitlon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppTuitlon/', include('AppTuitlon.urls')),
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppTuitlon/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

#Class del Tuitl
class Tuitl(models.Model):
    fecha = models.DateTimeField(default=datetime.now)
    contenido = models.TextField()
    imagen = models.ImageField(upload_to = 'avatares', null=True, blank=True)
    #img = models.FileField(upload_to = 'media')
    
#Class del Avatar
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to = 'avatares', null=True, blank=True)

    class Meta:
        verbose_name = "Avatar"
        verbose_name_plural = "Avatares"

AppTuitlon/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from AppTuitlon.models import Avatar
from AppTuitlon.models import Tuitl

class TuitlForm(forms.Form):

    contenido = forms.CharField(max_length=200)
    imagen = forms.ImageField()

class TuitlForm2(forms.ModelForm):

    class Meta:

        model = Tuitl
        fields = ['contenido', 'imagen']

class RegisterForm(UserCreationForm):

    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir Contraseña", widget=forms.PasswordInput)

    class Meta:

        model = User
        fields = ['username', 'email', 'password1', 'password2'] 


class AvatarForm(forms.ModelForm):

    class Meta:

        model = Avatar
        fields = ['user', 'imagen']

AppTuitlon/views.py
from django.shortcuts import render
from AppTuitlon.models import Tuitl, Avatar
from AppTuitlon.forms import TuitlForm, RegisterForm, AvatarForm, TuitlForm2
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate

#Vista para registrarse
def register(request):

    if request.method == 'POST':   

        form = RegisterForm(request.POST)  

        if form.is_valid():

            user=form.cleaned_data['username']
            form.save()
            
            return render(request, "AppTuitlon/inicio.html", {'mensaje':"Usuario Creado"})
    
    else:

        form = RegisterForm()   
    
    
    return render(request, "AppTuitlon/registrarse.html", {'form':form})

#Vusta para logearse
def login_request(request):

    if request.method == 'POST': 

        form = AuthenticationForm(request, data = request.POST) 

        if form.is_valid():
            
            usuario=form.cleaned_data.get('username')   
            contra=form.cleaned_data.get('password')    

            user=authenticate(username=usuario, password=contra)    

            if user:    

                login(request, user)   #hacemos login

                
                return render(request, "AppTuitlon/inicio.html", {'mensaje':f"Bienvenido {user}"}) 

        else:   
    
            return render(request, "AppTuitlon/inicio.html", {'mensaje':"Error. Datos incorrectos"})

    else:
            
        form = AuthenticationForm() #mostrar el formulario

    return render(request, "AppTuitlon/login.html", {'form':form})   


#Vista para ir al inicio
@login_required
def inicio(request):
    avatares = Avatar.objects.filter(user=request.user.id)

    return render(request,'AppTuitlon/inicio.html')

#Vista para poder tuitlear

@login_required
def tuitlear(request):

    if request.method == 'POST':

        miForm = TuitlForm2(request.POST, request.FILES)

        print(miForm)

        if miForm.is_valid:

            info = miForm.cleaned_data
          
            tuitl_a = Tuitl(contenido = info['contenido'], 
             imagen=info['imagen'])
    
            
            tuitl_a.save()
            
            return render(request, 'AppTuitlon/inicio.html')
    else:
        
        miForm = TuitlForm2()
    try:
        tuitl_a = Tuitl.objects.all()
    except:
        tuitl_a = None
    return render(request, 'AppTuitlon/tuitls.html', {'miForm':miForm})


#Class para ver todos los tuitls
class TuitlList(ListView):

      model = Tuitl 
      template_name = "AppTuitlon/tuitls_list.html"

#Class para ver tuitl particular
class TuitlDetalle(DetailView):

      model = Tuitl
      template_name = "AppTuitlon/tuitl_detalle.html"


#Class para borrar tuitls; quedó armada pero no se utilizará para no romper la estética simil Twitter
class TuitlDelete(DeleteView):

    model = Tuitl
    success_url = "/AppTuitlon/tuitl/list"




#Vista para subir avatares
@login_required
def addImg(request):

    if request.method == 'POST': 

        miForm = AvatarForm(request.POST, request.FILES) 

        if miForm.is_valid():

            info= miForm.cleaned_data

            avatar = Avatar(user=request.user, imagen=info['imagen'])

            avatar.save()

            return render(request, "AppTuitlon/inicio.html")

    else:

        miForm = AvatarForm()
    
    return render(request, "AppTuitlon/addImg.html", {'form':miForm})

#Vista para editar Usuarios
@login_required
def editUser(request):

    usuario = request.user 

    if request.method == "POST":   

        miForm = RegisterForm(request.POST) 

        if miForm.is_valid():

            info = miForm.cleaned_data     

           
            usuario.username = info['username']
            usuario.email = info['email']
            usuario.password1 = info['password1']
            usuario.password2 = info['password2']
            usuario.save()

            return render(request, "AppTuitlon/inicio.html")

    else:

        miForm= RegisterForm(initial={'username':usuario.username, 'email':usuario.email})

    return render(request, "AppTuitlon/editUser.html",{'miForm':miForm, 'usuario':usuario.username})

AppTuitlon/templates/AppTuitlon/addImg.html
{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<p>Acá agregamos imágenes.</p>

<form action="" method="POST" > {%csrf_token%}

        {{form.as_p}}



    <input type="submit", value="Subir Imagen", style="color:red">


</form>
{% endblock %}

AppTuitlon/templates/AppTuitlon/editUser.html
    
{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<body>    
    <title>Edición de usuario</title>

        {% if miForm.errors %}
        <p style="color: red;"> ESTAN MAL LOS DATOS</p>
        {% endif %}
        
        <form action="" method="POST"> {%csrf_token%}

            <table>
    
                {{miForm.as_table}}
    
            </table>
    
            <input type="submit", value="Enviar", style="color:red">
    
        </form>


    </body>

{% endblock %}

AppTuitlon/templates/AppTuitlon/inicio.html
{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}


{% endblock %}

AppTuitlon/templates/AppTuitlon/login.html
{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<head><title>Iniciar Sesión</title>
</head>
<body>
    <form action="" method="POST">   {% csrf_token %}
        
        {{form.as_p}}

        <button type="submit">Iniciar Sesión</button>

    </form>
</body>
    {% endblock %}

AppTuitlon/templates/AppTuitlon/logout.html
{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<head><title>Salir</title>
</head>
<body>
    Has cerrado sesión.
</body>
</html>
{% endblock %}

AppTuitlon/templates/AppTuitlon/padre.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
.w3-row-padding img {margin-bottom: 12px}

.w3-sidebar {width: 120px;background: #222;}

#main {margin-left: 120px}

@media only screen and (max-width: 600px) {#main {margin-left: 0}}
</style>
</head>
<body class="w3-black">

<!-- visualizacion de botones cuando la ventana es grande-->
<nav class="w3-sidebar w3-bar-block w3-small w3-hide-small w3-center">
  
  {% if not user.is_authenticated %}
  <a href="{% url 'Registrarse' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>REGISTRARSE</p>
  <a href="{% url 'Login' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>LOGUEARSE</p>
    {% endif %}
  {% if user.is_authenticated %}
    <p>Hola, {{user.username}}</p>
  
    
  <a href="{% url 'Inicio' %}" class="w3-bar-item w3-button w3-padding-large w3-black">
    <i class="fa fa-home w3-xxlarge"></i>
    <p>INICIO</p>
  </a>
  <a href="{% url 'Tuitlear' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>TUITLEAR</p>
 
<a href="{% url 'Subir Avatar' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>SUBIR AVATAR</p>
<a href="{% url 'Editar Usuario' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>EDITAR USUARIO</p>
<a href="{% url 'Logout' %}" class="w3-bar-item w3-button w3-padding-large w3-hover-black">
    <i class="fa fa-user w3-xxlarge"></i>
    <p>CERRAR SESIÓN</p>
    {% endif %}
   
    
  </a>
</nav>

<!-- visualizacion de botones cuando la ventana es más pequeña -->
<div class="w3-top w3-hide-large w3-hide-medium" id="myNavbar">
  <div class="w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small">
   
    {% if user.is_authenticated %}
     
    <a class="w3-bar-item w3-button" style="width:25% !important" href="{% url 'Inicio' %}">Inicio</a>
    <a class="w3-bar-item w3-button" style="width:25% !important" href="{% url 'Tuitlear' %}">Tuitlear</a>
    <a class="w3-bar-item w3-button" style="width:25% !important" href="{% url 'Subir Avatar' %}">Añadir Avatars</a>
    <a class="w3-bar-item w3-button" style="width:25% !important" href="{% url 'Editar Usuario' %}">Editar Usuario</a>
    <a class="w3-bar-item w3-button" style="width:25% !important" href="{% url 'Logout' %}">Cerrar Sesión</a>
    {% endif %}
    {% if not user.is_authenticated %}
    <a class="w3-bar-item w3-button" style="width:25% !important" href="{% url 'Registrarse' %}">Registrarse</a>
    <a class="w3-bar-item w3-button" style="width:25% !important" href="{% url 'Login' %}">Iniciar Sesión</a>
    {% endif %}


    
  </div>
</div>

<!-- Page Content -->
<div class="w3-padding-large" id="main">
  <!-- Header/Home -->
  <header class="w3-container w3-padding-32 w3-center w3-black" id="home">
    <h1 class="w3-jumbo"> Bienvenido a Tuitlon.</h1>
    {% block contenidoQueCambia%}

    {% endblock %}
    <!-- About Section -->
 <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
  <h2 class="w3-text-light-grey">Conócenos</h2>
  <hr style="width:200px" class="w3-opacity">
  <p>Bienvenido, terrícola. Aquí podrás compartir de manera anónima tu comportamiento basado en condicionamiento
    junto con otros bípedos hechos a base de carbono al igual que tú.
    Let's enjoy.
  </p>
  <h3 class="w3-padding-16 w3-text-light-grey">Nuestra web</h3>
  
  
  <div class="w3-row w3-center w3-padding-16 w3-section w3-light-grey">
    <div class="w3-quarter w3-section">
      <span class="w3-xlarge">Dudoso</span><br>
      Usuarios
    </div>
    <div class="w3-quarter w3-section">
      <span class="w3-xlarge">Más dudoso</span><br>
      Tuitls
    </div>
    <div class="w3-quarter w3-section">
      <span class="w3-xlarge">0 :(</span><br>
      Happy Clients
    </div>
    <div class="w3-quarter w3-section">
      <span class="w3-xlarge">100/100</span><br>
      Entusiasmo
    </div>
  </div>
    
  </header>
  
  
  <!-- Contact Section -->
  <div class="w3-padding-64 w3-content w3-text-grey" id="contact">
    <h2 class="w3-text-light-grey">Contact Me</h2>
    <hr style="width:200px" class="w3-opacity">

    <div class="w3-section">
      <p><i class="fa fa-map-marker fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Buenos Aires, Argentina</p>
      <p><i class="fa fa-phone fa-fw w3-text-white w3-xxlarge w3-margin-right"></i> Phone: +549 1173611440</p>
      <p><i class="fa fa-envelope fa-fw w3-text-white w3-xxlarge w3-margin-right"> </i> Email: gonzalojaguinagalde@mail.com</p>
    </div><br>
    <p>Let's get in touch. Send me a message:</p>

   
  <!-- End Contact Section -->
  </div>
  
    <!-- Footer -->
  <footer class="w3-content w3-padding-64 w3-text-grey w3-xlarge">
    <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
    
  <!-- End footer -->
  </footer>

<!-- END PAGE CONTENT -->
</div>

</body>
</html>

AppTuitlon/templates/AppTuitlon/registrarse.html
{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<p>Registrarse.</p>

<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}

    <button type="submit">Registrate</button>

</form>
{% endblock %}

AppTuitlon/templates/AppTuitlon/resultadoBusqueda.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Los tuitls de la pagina {{contenido}} son:</p>

    {% if tuitls %} 

    <ul>
    {% for x in tuitls %}

        <li>{{x.contenido}}</li>

    {% endfor %}

    </ul>

    {% endif %}    
</body>
</html>

AppTuitlon/templates/AppTuitlon/tuitl_Formularios.html
<!-- Formulario para cargar tuit -->



{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
    <body>    
    <title>Tuitls - Agregar Tuitl</title>

        {% if miForm.errors %}
        <p style="color: red;"> ESTAN MAL LOS DATOS</p>
        {% endif %}
        
        <form action="" method="POST"> {% csrf_token %}
            
            <input>

                {{ miForm.as_table }}

        </input>

            <input type="submit" value="Ok">
        </form>


    </body>
    {% endblock %}

AppTuitlon/templates/AppTuitlon/tuitl_confirm_delete.html
<!-- Esta todavia no esta terminada, en para editar, habria que verla, esta igual al powerpoint -->


{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<head><title>Tuitl Borrar</title>
</head>
<body>


    <form method="post">{% csrf_token %}
        ¿Estás seguro que deseas borrar el tuitl "{{ tuitl }}"?
        <input type="submit" value="Borrar" />
        <a href="{% url 'List' %}">Regresar</a>
    </form>

    
</body>
{% endblock %}

AppTuitlon/templates/AppTuitlon/tuitl_detalle.html
<!-- Esta todavia no esta terminada, en para editar, habria que verla, esta igual al powerpoint -->


{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<head><title>Tuitl Detalle</title>
</head>
<body>


   
    <p><i>{{ tuitl.fecha }}
        {{ tuitl.contenido }}{% if tuitl.imagen %}
        <img src="{{tuitl.imagen.url}}">
        {% endif %}<p></i></p>
    <p><i></i></p>
    <p>
        <a href="{% url 'List' %}">Regresar</a>
        <a href="{% url 'Delete' tuitl.id %}">Borrar</a> 
    </p>

    
</body>
{% endblock %}

AppTuitlon/templates/AppTuitlon/tuitl_form.html
{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}
<head><title>Tuitl formulario</title>
</head>
<body class="w3-black">


    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar" />
    </form>


    
</body>
{% endblock %}

AppTuitlon/templates/AppTuitlon/tuitls.html
<!-- Esto es para subir tuitls -->



{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    {% if miForm.errors %}

    <div>
        <p style="color: red;"> Estan mal los datos, revisar </p>

    {% endif %}

    <h1>Tuitls - Agregar Tuitl</h1>

    {% if miForm.errors %}
    <p style="color: red;"> ESTAN MAL LOS DATOS</p>
    {% endif %}
    
    <form action="" enctype="multipart/form-data" method="POST"> {% csrf_token %}
        
        <p class="w3-input w3-padding-16"><table>

            {{ miForm.as_table }}

        </table></p>

        <input type="submit" value="Enviar">
    </form>
    <a href="{% url 'List' %}">Ver tuitls</a>
{% endblock %}

AppTuitlon/templates/AppTuitlon/tuitls_list.html
<!-- Esta todavia no esta terminada, en para editar, habria que verla, esta igual al powerpoint -->


{% extends "AppTuitlon/padre.html" %}

{% load static %}

{% block contenidoQueCambia %}

    <title>Tuitls de Tuitlon - Python</title>
    <ul>
        {% for tuitl in tuitl_list %}

            <li>
                <p>{{ tuitl.fecha }}
                    {{ tuitl.contenido }}</p> 
                    {% if tuitl.imagen %}
                    <img src="{{tuitl.imagen.url}}">
                    {% endif %}<p> 
                    <a href="{% url 'Detail' tuitl.id %}">Ver</a>
                    
                
                </p> 
            </li>

        {% endfor %}
    </ul>

   
    </from>
    {% endblock %}